USE vaccine_erp;
CREATE TABLE hospital (
	id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	orgcd VARCHAR(64) NOT NULL,
	orgnm VARCHAR(200) NOT NULL,
    orgTlno VARCHAR(64) NOT NULL,
    sido VARCHAR(200) NOT NULL,
    si VARCHAR(200) NOT NULL,
    orgZipaddr VARCHAR(200) NOT NULL,
    slrYmd VARCHAR(64) NOT NULL,
    dywk VARCHAR(64) NOT NULL,
    hldyYn VARCHAR(64) NOT NULL,
    lunchSttTm VARCHAR(64),
    lunchEndTm VARCHAR(64),
    sttTm VARCHAR(64),
    endTm VARCHAR(64)
);